# Generated by Django 6.0.6 on 2026-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hall_name",
                    models.CharField(default="القاعة الملكية", max_length=100),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="أفخم قاعات المناسبات في المدينة",
                        max_length=150,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="دمشق، اتستراد المزة", max_length=200
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+966 11 XXX XXXX", max_length=30
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, default="rosepalace-riyadh.com", max_length=100
                    ),
                ),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3624.6504858736247!2d46.67255391499984!3d24.68773398413143!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e2f03890d489399%3A0xba974d1c98e79fd5!2sKing%20Abdullah%20Road%2C%20Riyadh!5e0!3m2!1sar!2ssa!4v1620000000000!5m2!1sar!2ssa",
                        max_length=1000,
                    ),
                ),
                (
                    "directions_url",
                    models.URLField(
                        blank=True,
                        default="https://maps.google.com/?q=King+Abdullah+Road+Riyadh",
                        max_length=500,
                    ),
                ),
                (
                    "stat1_value",
                    models.CharField(blank=True, default="500+", max_length=20),
                ),
                (
                    "stat1_label",
                    models.CharField(
                        blank=True, default="طاقة استيعابيّة", max_length=50
                    ),
                ),
                (
                    "stat2_value",
                    models.CharField(blank=True, default="5★", max_length=20),
                ),
                (
                    "stat2_label",
                    models.CharField(blank=True, default="قاعة فاخرة", max_length=50),
                ),
                (
                    "stat3_value",
                    models.CharField(blank=True, default="3", max_length=20),
                ),
                (
                    "stat3_label",
                    models.CharField(blank=True, default="صالات أفراح", max_length=50),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
