# Generated by Django 6.0.6 on 2026-08-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0002_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="tagline",
            field=models.CharField(
                blank=True, default="أفخم قاعات المناسبات في دمشق", max_length=150
            ),
        ),
    ]
