# Generated by Django 6.0.6 on 2026-08-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0003_alter_venue_tagline"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groom_name", models.CharField(default="جمال", max_length=50)),
                ("bride_name", models.CharField(default="سوار", max_length=50)),
                (
                    "wedding_datetime",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 10, 10, 18, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "hero_date_line",
                    models.CharField(
                        blank=True, default="السبت، العاشر من أوكتوبر", max_length=100
                    ),
                ),
                (
                    "hero_year_line",
                    models.CharField(
                        blank=True, default="ألفان وستة وعشرون", max_length=50
                    ),
                ),
                (
                    "ceremony_time_range",
                    models.CharField(
                        blank=True, default="5:00 م - 10:00 م", max_length=50
                    ),
                ),
                (
                    "doors_open_note",
                    models.CharField(
                        blank=True,
                        default="الأبواب تُفتح الساعة 4:30 م",
                        max_length=100,
                    ),
                ),
                (
                    "story_intro",
                    models.CharField(
                        blank=True,
                        default="كل قصة حبٍّ جميلة، لكن قصتنا هي المفضّلة لدينا",
                        max_length=200,
                    ),
                ),
                (
                    "milestone1_date",
                    models.CharField(blank=True, default="03-09-2025", max_length=30),
                ),
                (
                    "milestone1_title",
                    models.CharField(blank=True, default="أول لقاء", max_length=100),
                ),
                (
                    "milestone1_description",
                    models.TextField(
                        blank=True,
                        default="تحت سماءٍ مرصّعة بالنجوم، تلاقت نظرتان فكانت أول حروف قصةٍ لم تُكتب بعد.",
                    ),
                ),
                (
                    "milestone2_date",
                    models.CharField(blank=True, default="10-10-2025", max_length=30),
                ),
                (
                    "milestone2_title",
                    models.CharField(blank=True, default="ليلة الخطبة", max_length=100),
                ),
                (
                    "milestone2_description",
                    models.TextField(
                        blank=True,
                        default="ليلةٌ لمع فيها الخاتم على الإصبع، وكان بريق العيون أصدق من بريق الذهب.",
                    ),
                ),
                (
                    "milestone3_date",
                    models.CharField(blank=True, default="10-10-2026", max_length=30),
                ),
                (
                    "milestone3_title",
                    models.CharField(blank=True, default="بداية الأبد", max_length=100),
                ),
                (
                    "milestone3_description",
                    models.TextField(
                        blank=True,
                        default="ها هي اللحظة التي طال انتظارها: أن تتحوّل القصة إلى عهدٍ، والحب إلى رحلةٍ تدوم إلى الأبد.",
                    ),
                ),
                (
                    "program1_time",
                    models.CharField(blank=True, default="5:00 م", max_length=20),
                ),
                (
                    "program1_title",
                    models.CharField(
                        blank=True, default="استقبال الضيوف", max_length=100
                    ),
                ),
                (
                    "program1_description",
                    models.CharField(
                        blank=True,
                        default="استقبال حارّ مع المرطّبات والموسيقى الحيّة",
                        max_length=200,
                    ),
                ),
                (
                    "program2_time",
                    models.CharField(blank=True, default="6:00 م", max_length=20),
                ),
                (
                    "program2_title",
                    models.CharField(
                        blank=True, default="حفل عقد القران", max_length=100
                    ),
                ),
                (
                    "program2_description",
                    models.CharField(
                        blank=True,
                        default="مراسم العقد المقدّس في القاعة الكبرى",
                        max_length=200,
                    ),
                ),
                (
                    "program3_time",
                    models.CharField(blank=True, default="7:00 م", max_length=20),
                ),
                (
                    "program3_title",
                    models.CharField(
                        blank=True, default="جلسة تصوير تذكاريّة", max_length=100
                    ),
                ),
                (
                    "program3_description",
                    models.CharField(
                        blank=True,
                        default="توثيق اللحظات الجميلة مع العروسين",
                        max_length=200,
                    ),
                ),
                (
                    "program4_time",
                    models.CharField(blank=True, default="8:00 م", max_length=20),
                ),
                (
                    "program4_title",
                    models.CharField(
                        blank=True, default="عشاء وسهرة الاحتفال", max_length=100
                    ),
                ),
                (
                    "program4_description",
                    models.CharField(
                        blank=True,
                        default="عشاء فاخر يليه رقص واحتفال بهيج",
                        max_length=200,
                    ),
                ),
                (
                    "footer_quote",
                    models.CharField(
                        blank=True,
                        default="الزواج ليس اسماً؛ إنه فعلٌ. إنه الطريقة التي تُحبّ بها شريك حياتك كلّ يوم",
                        max_length=300,
                    ),
                ),
                (
                    "hashtag",
                    models.CharField(
                        blank=True, default="#جمال_وسوار_2026", max_length=50
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
