# Generated by Django 6.0.6 on 2026-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0004_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("square", "Square"),
                            ("tall", "Tall"),
                            ("wide", "Wide"),
                        ],
                        default="square",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
