# Generated by Django 6.0.6 on 2026-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0005_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="music/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
