# Generated by Django 6.0.6 on 2026-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0006_sitemusic"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bride_father_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="groom_father_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_quran_reference",
            field=models.CharField(
                blank=True, default="سورة الروم - الآية 21", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_quran_verse",
            field=models.CharField(
                blank=True,
                default="وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَوَدَّةً وَرَحْمَةً",
                max_length=300,
            ),
        ),
    ]
