# Generated by Django 6.0.6 on 2026-08-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wedding_invitaion", "0007_sitesettings_bride_father_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="dietary",
        ),
    ]
